### ISSUE TITLE
cannot use md5collgen in cloud VM

### ISSUE THREAD

**Issue by hooper625** [seed-labs/seed-labs#113]
I have uploaded the md5collgen file in my Google VM but the:
"md5collgen -p prefix.txt -o out1.bin out2.bin" command results in: 
"md5collgen: command not found". I am not sure how to run this lab and my professor does not either. I am at a loss.

**Comment by kevin-w-du** [comment]
This is not a place to post the problem encountered when you do the lab, or it will be flooded by problems like this. Unless you are very sure it is the problem with the lab design, you can post it here. However, your problem is simply an operation error that you should try to solve by yourself or with the help of your professor (finding how to run this command is part of the lab).
