### ISSUE TITLE
ARM Mac Ubuntu Link Update

### ISSUE THREAD

**Issue by sethbarrett50** [seed-labs/seed-labs#149]
Currently, step 3 in [Apple Arm SeedVM Fusion Guide](https://github.com/seed-labs/seed-labs/tree/master/lab-setup/apple-arm)
/seedvm-fusion.md) contains references to installing Ubuntu 22.04.3 LTS (Jammy Jellyfish) Daily Build, along side a link and image. The current link points to Ubuntu 22.04.4 LTS (Jammy Jellyfish) Daily Build. Either the image and link text need to be updated to reflect 22.04.4 if this works, or the link should be updated to point at the Ubuntu 22.04.4 LTS (Jammy Jellyfish) Daily Build download location. 

<img width="807" alt="image" src="https://github.com/user-attachments/assets/e2463255-555e-4ca0-9be5-45dd5376c982">

**Comment by sethbarrett50** [comment]
I couldn't find any other issues addressing this, but if this is already a known issue, apologies for the issue replication

**Comment by sethbarrett50** [comment]
Apologies if this has been already addressed. I didn't see any other issues pointing this out, and was unsure if the 22.04.4 version would work with seed labs.

**Comment by dstkibrom** [comment]
I have set up the lab in my mac M2 chip by following the steps shown below. 

1. Download and install VMware Fusion (same as the seedlabs)
2. Download ubuntu server instead of ubuntu desktop for AArch64/ARMv8 from the official ubuntu server site https://cdimage.ubuntu.com/releases/22.04/release/

2. the install ubuntu desktop using the following commands 

`sudo apt-get update
sudo apt-get install ubuntu-desktop`

3. reboot the OS 
4. then follow the official seedlabs page starting from setup bidirectional shared clipboard https://github.com/seed-labs/seed-labs/blob/master/lab-setup/apple-arm/seedvm-fusion.md#setup-bidirectional-shared-clipboard
