### ISSUE TITLE
SEED Lab development: clickjacking

### ISSUE THREAD

**Issue by cole-wustl** [seed-labs/seed-labs#30]
My co-instructor and I have a student group in an Intro to Security class who, for a class project, are designing a clickjacking lab after the model of the SEED labs we've done in class.  What would be the best way to collaborate and see whether the SEED Project would be interested in including their work?  Happy to connect the group and discuss midstream or wait until the assignment is fully functional and present it then for a look.

**Comment by kevin-w-du** [comment]
I will be very interested in including this lab in the SEED project. Once it is in a stable state, you can add a a folder in the `category-web` and commit the source file to the github repo. You may need to define a different copyright block, because the authors are different. I will also list the lab to the SEED website, so it can reach a broader audience (I will revise the website, so the author names are presented).

**Comment by cole-wustl** [comment]
Sounds good, thanks and will do!
