### ISSUE TITLE
Some questions about "Containerizing SEED Labs (SEED Labs 2.0)"

### ISSUE THREAD

**Issue by Jacob953** [seed-labs/seed-labs#75]
I find there is no place for using container on [Lab Setup](https://seedsecuritylabs.org/labsetup.html), so I fork seed-labs to look for a guide. But I didn't understand whether container had done or not on [lab-setup](https://github.com/seed-labs/seed-labs/tree/master/lab-setup#containerizing-seed-labs-seed-labs-20)

Is there any specific steps for container lab-setup on my macOS?

thanks in advance.

**Comment by kevin-w-du** [comment]
We do have manuals regarding docker here: https://github.com/seed-labs/seed-labs/blob/master/manuals/docker/SEEDManual-Container.md. This manual is linked to each lab that needs containers. 

We don't have manuals for setting up the containers on macOS. We expect students to do the SEED labs from the provided SEED VM, instead of from their own host machines.

**Comment by Jacob953** [comment]
Turns out I got it wrong
Thanks a lot.😊
